'use client';

import { useState, type FormEvent } from 'react';
import SidebarNav from '@/components/sidebar-nav';
import { MessageSquare, Copy, Download } from 'lucide-react';

type ResponseTone = 'Professional' | 'Friendly' | 'Sales-focused' | 'Support';

function getAuthHeaders(): Record<string, string> {
  if (typeof window === 'undefined') return {};
  const token = window.localStorage.getItem('authToken');
  return token ? { Authorization: `Bearer ${token}` } : {};
}

export default function ResponsesPage() {
  const [customerMessage, setCustomerMessage] = useState('');
  const [tone, setTone] = useState<ResponseTone>('Professional');
  const [response, setResponse] = useState('');
  const [loading, setLoading] = useState(false);

  const toneInstructions: Record<ResponseTone, string> = {
    Professional: 'Write a professional, formal response suitable for business correspondence.',
    Friendly: 'Write a warm, conversational response that feels personal and approachable.',
    'Sales-focused': 'Write a persuasive response that encourages the customer to take action.',
    Support: 'Write a helpful, empathetic support response that addresses the customer concern.'
  };

  async function handleSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    if (!customerMessage.trim()) return;

    setLoading(true);
    setResponse('');

    try {
      const res = await fetch('/api/ai', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...getAuthHeaders() },
        body: JSON.stringify({
          prompt: `Customer message: "${customerMessage}"

${toneInstructions[tone]}

Write a concise, professional reply with:
- Proper greeting
- Direct answer to their question/concern
- Clear next steps or call to action
- Professional sign-off`
        })
      });

      const json = await res.json();
      setResponse(json.text || json.error || 'No response generated.');
    } catch {
      setResponse('Failed to generate response. Please try again.');
    } finally {
      setLoading(false);
    }
  }

  function downloadTXT() {
    if (!response) return;
    
    const formattedResponse = `CUSTOMER RESPONSE
${'='.repeat(40)}

${response}

${'='.repeat(40)}
Generated by Estech AI Copilot
${new Date().toLocaleString()}`;
    
    const blob = new Blob([formattedResponse], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `customer-response-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  return (
    <div className="min-h-screen bg-slate-950">
      <SidebarNav />
      
      <main className="lg:pl-64">
        <div className="px-6 py-8 lg:px-12">
          {/* Header */}
          <div className="max-w-4xl">
            <div className="flex items-center gap-3">
              <MessageSquare className="h-8 w-8 text-sky-400" />
              <h1 className="text-2xl font-bold text-white">Communication Studio</h1>
            </div>
            <p className="mt-2 text-slate-400">
              AI-powered responses for WhatsApp, email, and support tickets.
            </p>
          </div>

          {/* Main Grid */}
          <div className="mt-8 grid gap-8 lg:grid-cols-2">
            {/* Input Panel */}
            <div className="space-y-6">
              <div>
                <label className="block text-sm font-medium text-slate-200">Customer message</label>
                <textarea
                  value={customerMessage}
                  onChange={(e) => setCustomerMessage(e.target.value)}
                  placeholder="Paste WhatsApp message, email, or customer inquiry..."
                  rows={6}
                  className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-900 px-4 py-2.5 text-slate-100 outline-none focus:border-sky-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-200 mb-2">Response tone</label>
                <div className="grid grid-cols-2 gap-2">
                  {(['Professional', 'Friendly', 'Sales-focused', 'Support'] as ResponseTone[]).map((t) => (
                    <button
                      key={t}
                      type="button"
                      onClick={() => setTone(t)}
                      className={`rounded-lg border px-3 py-2 text-xs font-medium transition ${
                        tone === t
                          ? 'border-sky-500 bg-sky-500/20 text-sky-300'
                          : 'border-slate-700 text-slate-300 hover:border-slate-600'
                      }`}
                    >
                      {t}
                    </button>
                  ))}
                </div>
              </div>

              <button
                type="submit"
                onClick={handleSubmit as any}
                disabled={loading}
                className="inline-flex w-full items-center justify-center rounded-lg bg-sky-500 px-5 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-sky-400 disabled:cursor-not-allowed disabled:opacity-60"
              >
                {loading ? 'Generating...' : 'Generate reply'}
              </button>
            </div>

            {/* Output Panel */}
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h2 className="text-sm font-semibold uppercase tracking-wider text-slate-400">Generated reply</h2>
                {response && (
                  <div className="flex gap-2">
                    <button
                      onClick={() => navigator.clipboard.writeText(response)}
                      className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs text-slate-300 hover:bg-slate-800"
                    >
                      <Copy className="h-3.5 w-3.5" />
                      Copy
                    </button>
                    <button
                      onClick={downloadTXT}
                      className="flex items-center gap-1.5 rounded-lg bg-sky-500 px-3 py-1.5 text-xs font-medium text-slate-950 hover:bg-sky-400"
                    >
                      <Download className="h-3.5 w-3.5" />
                      Download
                    </button>
                  </div>
                )}
              </div>

              <div className="rounded-lg border border-slate-800 bg-slate-900/50 p-6 min-h-[200px] font-sans text-sm">
                {loading ? (
                  <div className="space-y-3">
                    <div className="h-4 w-full animate-pulse rounded bg-slate-800" />
                    <div className="h-4 w-5/6 animate-pulse rounded bg-slate-800" />
                    <div className="h-4 w-3/4 animate-pulse rounded bg-slate-800" />
                    <div className="h-4 w-4/5 animate-pulse rounded bg-slate-800" />
                  </div>
                ) : response ? (
                  <pre className="whitespace-pre-wrap break-words leading-relaxed text-slate-200">{response}</pre>
                ) : (
                  <p className="text-slate-400">Your professional reply will appear here.</p>
                )}
              </div>

              <div className="flex gap-2">
                <button
                  onClick={() => setCustomerMessage('Hi, I\'m interested in your website design package. How much does it cost?')}
                  className="flex-1 rounded-lg border border-slate-800 px-3 py-2 text-xs text-slate-300 hover:border-slate-700"
                >
                  Sales inquiry
                </button>
                <button
                  onClick={() => setCustomerMessage('I have an issue with my order. It hasn\'t arrived yet!')}
                  className="flex-1 rounded-lg border border-slate-800 px-3 py-2 text-xs text-slate-300 hover:border-slate-700"
                >
                  Complaint
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}