-- Migration 14: Content Studio
-- Marketing content generation and library

CREATE TABLE public.content (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  workspace_id UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT 'Untitled Content',
  type TEXT NOT NULL DEFAULT 'social_media_post',
  goal TEXT,
  audience TEXT,
  prompt TEXT,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by UUID NOT NULL REFERENCES auth.users(id),
  updated_by UUID REFERENCES auth.users(id)
);

CREATE INDEX IF NOT EXISTS idx_content_workspace_id ON public.content(workspace_id);
CREATE INDEX IF NOT EXISTS idx_content_type ON public.content(type);
CREATE INDEX IF NOT EXISTS idx_content_created_at ON public.content(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_content_created_by ON public.content(created_by);

CREATE TRIGGER update_content_updated_at BEFORE UPDATE ON public.content
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE POLICY "Members can view content" ON public.content
  FOR SELECT USING (public.is_workspace_member(workspace_id, auth.uid()));

CREATE POLICY "Members can create content" ON public.content
  FOR INSERT WITH CHECK (public.is_workspace_member(workspace_id, auth.uid()) AND auth.uid() = created_by);

CREATE POLICY "Members can update own content" ON public.content
  FOR UPDATE USING (public.is_workspace_member(workspace_id, auth.uid()) AND auth.uid() = created_by);

CREATE POLICY "Members can delete own content" ON public.content
  FOR DELETE USING (public.is_workspace_member(workspace_id, auth.uid()) AND auth.uid() = created_by);

COMMENT ON TABLE public.content IS 'Marketing content generated by Content Studio';
